<?php

/**
 * @file
 * Provides a geo entity type.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function geo_entity_theme() {
  return [
    'geo_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for geo templates.
 *
 * Default template: geo-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the geo information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_geo_entity(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function geo_entity_field_widget_complete_entity_browser_entity_reference_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  if ($context['widget']->getSetting('entity_browser') == 'geo_entity_library') {
    $field_widget_complete_form['#attached']['library'][] = 'geo_entity/geobrowser';
    $field_widget_complete_form['#attributes']['class'][] = 'geo-entity-geobrowser';
  }
}

/**
 * After build geofield_map element.
 *
 * @see geo_entity_field_widget_form_alter()
 */
function _geo_entity_geofield_widget_alter($element) {
  unset($element['value']['map']['geocode']);
  return $element;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function geo_entity_theme_suggestions_geo_entity(array $variables) {
  $suggestions = [];

  $geo = $variables['elements']['#geo_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'geo_entity__' . $sanitized_view_mode;
  $suggestions[] = 'geo_entity__' . $geo->bundle();
  $suggestions[] = 'geo_entity__' . $geo->bundle() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * This removes entity forms if the bundle is not enabled for the field.
 * There are a few patches in the issue queue to remove the need to do this.
 * The most promising:
 *   https://www.drupal.org/project/entity_browser/issues/2765295
 */
function geo_entity_form_entity_browser_geo_entity_library_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $storage = $form_state->getStorage();
  $bundles = $storage['entity_browser']['widget_context']['target_bundles'];
  // UUIDs are defined by the configuration we're installing.
  // @see config/install/entity_browser.browser.geo_entity_library.yml
  if (empty($bundles['address'])) {
    unset($form['widget_selector']['tab_selector_3edf0a0f-cb61-4324-8d36-1898e23a16ed']);
  }
  if (empty($bundles['area'])) {
    unset($form['widget_selector']['tab_selector_beda8d11-9000-4069-95e7-dbb4282941db']);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function geo_entity_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'geo_entity_library') {
    $view->element['#attached']['library'][] = 'geo_entity/geobrowser';
  }
}

/**
 * Implements hook_geofield_map_latlon_element_alter().
 *
 * Adds JS event handler to Geofield Map lon lat fields for geocoder.
 */
function geo_entity_geofield_map_latlon_element_alter(array &$map_settings, array &$complete_form, array &$form_state_values) {
  $complete_form['#attached']['library'] = 'geo_entity/geocode-geofield';
  $complete_form['#attached']['drupalSettings']['geoEntityGeocode']['geofield'][$complete_form['#id']] = [
    'lon' => $map_settings['lngid'],
    'lat' => $map_settings['latid'],
  ];
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 *
 * Adds JS event handler to Leaflet fields for geocoder.
 */
function geo_entity_field_widget_single_element_leaflet_widget_default_form_alter(&$element, FormStateInterface $form_state, $context) {
  $element['map']['#attached']['drupalSettings']['geoEntityGeocode']['leaflet'][Html::getId($form_state->getFormObject()->getFormId())] = $element['map']['#map_id'];
  $element['map']['#attached']['library'][] = 'geo_entity/geocode-leaflet';
}
